Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
    config.vm.hostname = "debian-testing"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jrmsdev-debian-testing"
    end

    config.vm.provision "distupgrade", type: "shell",
            path: "../scripts/debian-upgrade.sh",
            args: ["testing", "main"]

    config.vm.provision "sshauth", type: "shell",
        path: "../scripts/vagrant-sshauth.sh"
end
