Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
    config.vm.hostname = "debian-stable"
    config.vm.provision "distupgrade", type: "shell",
            path: "../scripts/debian-upgrade.sh",
            args: ["stable", "main"]
end
