Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|

    config.vm.box = "jrmsdev/debian-testing"
    config.vm.hostname = "debian-gomobile"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jrmsdev-debian-gomobile"
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "dist-upgrade", type: "shell",
        path: "../scripts/debian-upgrade.sh",
        args: ["testing"]

    config.vm.provision "apt-install", type: "shell",
        path: "../scripts/debian-install.sh",
        args: ["rsync", "wget", "pkg-config", "git", "golang", "gradle",
               "libgles2-mesa-dev"]

    config.vm.provision "golang-setup", type: "shell",
        path: "./golang-setup.sh"

    config.vm.provision "file", source: "./gomobile-setup.sh",
        destination: "/home/vagrant/bin/gomobile-setup.sh"

    config.vm.provision "gomobile-setup", type: "shell", inline: <<-SHELL
        chown -R vagrant:vagrant ~vagrant/bin
        chmod 0750 ~vagrant/bin/gomobile-setup.sh
    SHELL

    config.vm.provision "minimize", type: "shell",
        run: "never",
        path: "../scripts/minimize.sh"

    config.vm.provision "sshauth", type: "shell",
        run: "never",
        path: "../scripts/vagrant-sshauth.sh"
end
