Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|

    config.vm.box = "jrmsdev/debian-stable"
    config.vm.hostname = "kivy-buildozer"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jrmsdev-kivy-buildozer"
    end

    # buildozer serve (port 8000)
    config.vm.network "forwarded_port", guest: 8000, host: 8000

    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
        mkdir -vp /build
        chown -v vagrant:vagrant /build
        rm -vf ~vagrant/.buildozer
        ln -vs /build ~vagrant/.buildozer
    SHELL

    config.vm.provision "i386arch", type: "shell",
        inline: "dpkg --add-architecture i386"

    config.vm.provision "debinstall", type: "shell",
        path: "../scripts/debian-install.sh",
        args: ["rsync",
               "python-kivy",
               "cython",
               "default-jdk-headless",
               "python-pip",
               "python-setuptools",
               "python-wheel",
               "build-essential",
               "ccache",
               "git",
               "libncurses5:i386",
               "libstdc++6:i386",
               "libgtk2.0-0:i386",
               "libpangox-1.0-0:i386",
               "libpangoxft-1.0-0:i386",
               "libidn11:i386",
               "python2.7",
               "python2.7-dev",
               "openjdk-8-jdk",
               "unzip",
               "zlib1g-dev",
               "zlib1g:i386"]

    config.vm.provision "pipinstall", type: "shell",
        path: "../scripts/pip-install.sh",
        args: ["buildozer>=0.33"]

    config.vm.provision "sshauth", type: "shell",
        path: "../scripts/vagrant-sshauth.sh"
end
