Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|

    config.vm.box = "jrmsdev/debian-testing"
    config.vm.hostname = "kivy-buildozer"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jrmsdev-kivy-buildozer"
    end

    # buildozer serve (port 8000)
    config.vm.network "forwarded_port", guest: 8000, host: 8000

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "dist-upgrade", type: "shell",
        path: "../scripts/debian-upgrade.sh",
        args: ["testing"]

    config.vm.provision "dpkg-i386arch", type: "shell",
        inline: "dpkg --add-architecture i386"

    config.vm.provision "apt-install", type: "shell",
        path: "../scripts/debian-install.sh",
        args: ["rsync",
               "pkg-config",
               "autoconf",
               "automake",
               "libtool",
               "python2.7",
               "python2.7-dev",
               "openjdk-8-jdk",
               "python-pip",
               "python-setuptools",
               "python-wheel",
               "build-essential",
               "ccache",
               "git",
               "unzip",
               "zlib1g-dev",
               "libncurses5:i386",
               "libstdc++6:i386",
               "libgtk2.0-0:i386",
               "libpangox-1.0-0:i386",
               "libpangoxft-1.0-0:i386",
               "libidn11:i386",
               "zlib1g:i386"]

    config.vm.provision "pip-install", type: "shell",
        path: "../scripts/pip-install.sh",
        args: ["Cython==0.25.2", "buildozer>=0.33"]

    config.vm.provision "buildozer-setup", type: "shell", inline: <<-SHELL
        mkdir -vp /buildozer/bin /buildozer/android/platform /build
        chown -vR vagrant:vagrant /buildozer /build
        rm -vf ~vagrant/.buildozer
        ln -vs /buildozer ~vagrant/.buildozer
    SHELL

    config.vm.provision "minimize", type: "shell",
        run: "never",
        path: "../scripts/minimize.sh"

    config.vm.provision "sshauth", type: "shell",
        run: "never",
        path: "../scripts/vagrant-sshauth.sh"
end
