Vagrant.require_version ">=2.0.0"

Vagrant.configure("2") do |config|
    config.vm.box = "jrmsdev/debian-stable"
    config.vm.hostname = "debian-packaging"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jrmsdev-debian-packaging"
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "/opt/src/debpkg", "/build", type: "rsync"

    config.vm.provision "distupgrade", type: "shell",
        path: "../scripts/debian-upgrade.sh",
        args: ["unstable", "main"]

    config.vm.provision "aptinstall", type: "shell",
        path: "../scripts/debian-install.sh",
        args: ["git-dpm", "dh-make", "dh-systemd", "quilt", "pristine-tar",
               "vim-tiny", "fakeroot", "lintian", "sbuild", "schroot", "python3-setuptools", "debootstrap"]

    config.vm.provision "sbuild-setup", inline: <<-SHELL
        sbuild-adduser vagrant
        sbuild-createchroot sid /srv/chroot/unstable-amd64 \
            --alias=unstable --alias=UNRELEASED \
            http://deb.debian.org/debian
    SHELL

    config.vm.provision "minimize", type: "shell",
        run: "never",
        path: "../scripts/minimize.sh"

    config.vm.provision "sshauth", type: "shell",
        run: "never",
        path: "../scripts/vagrant-sshauth.sh"
end
